### ISSUE TITLE
Validation Fails

### ISSUE THREAD

**Issue by rbottoms** [mhdhejazi/CoronaTracker#101]
I have the latest Xcode version, my code base is basically the same as yours. The change I made is not related to the problem libraries:

App Store Connect Operation Error
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'CSV' under the iOS application 'CovidIntel.app'.

App Store Connect Operation Error
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Disk' under the iOS application 'CovidIntel.app'.

App Store Connect Operation Error
Invalid Bundle. The bundle at 'CovidIntel.app/PlugIns/Widget.appex' contains disallowed nested bundles.

App Store Connect Operation Error
Invalid Bundle. The bundle at 'CovidIntel.app/PlugIns/Widget.appex' contains disallowed file 'Frameworks'.

**Comment by mhdhejazi** [comment]
This is a validation issue from the App Store side, and the app isn't really affected, so I'd suggest trying the solutions posted by those who had a similar issue.
This is a good starting point: https://stackoverflow.com/questions/30361864/invalid-bundle-the-bundle-contains-disallowed-nested-bundles-contains-disallow

If none of the solutions works, I'd suggest contacting Apple Support.

I'm sorry. This is all I can do to help.
