### ISSUE TITLE
history for daily data

### ISSUE THREAD

**Issue by srt10coupe** [mhdhejazi/CoronaTracker#104]
after a period of 24 hours, the data (look screenshot) will be reset. it would be good if you could choose past days. what there were the maximum values (all values) before the 24h period reset.

sorry for the bad english 

 ![image](https://user-images.githubusercontent.com/399997/80134188-a9e67080-859e-11ea-8e22-4b3b9b8573ef.jpeg)

**Comment by mhdhejazi** [comment]
You can see that in the second chart (Daily New Cases). And you can switch between confirmed cases and deaths from the menu.
Is that what you are looking for?
![image](https://user-images.githubusercontent.com/121827/80161685-d8ce0800-85d9-11ea-80e3-cecaa067ee02.jpeg)

**Comment by srt10coupe** [comment]
thx 🙈
