### ISSUE TITLE
Bar title in "Daily New Cases" fails for USA

### ISSUE THREAD

**Issue by Jimmysnielsen** [mhdhejazi/CoronaTracker#129]
Opening the USA graph "DAILY NEW CASES" and clicking on an individual bar yields  MMM YYYY NN e.g. "May 2020: 25,4K" whereas the same graph for MEXICO says MMM DD NN e.g. "May 23: 3,3k". The latters seems most appropriate.
I am using version 1.7.1 on Mac Catalina 10.15.6

**Comment by mhdhejazi** [comment]
You are right about this. It's fixed now on the master.
