### ISSUE TITLE
Use current math to estimate infected but not reported on city level

### ISSUE THREAD

**Issue by nateritter** [mhdhejazi/CoronaTracker#13]
**Story:** As a user, I would like to know what the estimated infected but not reported is, ideally on a city level, but even on a state level for starters would be helpful.  Sources for the math can be provided if needed, but a couple inputs would be fine as well.

**Comment by MhdHejazi** [comment]
But how could such estimates be calculated if we only know the confirmed (and reported) cases, and have no idea about the actual number?

**Comment by nateritter** [comment]
Ref: https://medium.com/@tomaspueyo/coronavirus-act-today-or-people-will-die-f4d3d9cd99ca (there's a link there for a spreadsheet you can make a copy of and use as a model)

A couple of quick assumptions the article makes at the time of it's writing, in bullet points (starting with mortality rate in WA state):
* 22 deaths
* 17.3 days on average from cases to death
* 1% mortality rate (of cases)
* 6.2 doubling time for cases

Thus: `2^(17/6) = 8`.
This means that one death = 800 true cases. 

This could be backed out using the same assumptions to number of reported cases to get number of unreported cases.

**Comment by MhdHejazi** [comment]
Great article and analysis. Thank you for sharing.

The estimation model totally makes sense, but I think it's only valid when the virus spreads in an uncontrolled way and without any intervention from the government.

Since that is not the case now, I guess the model will give us an overestimate. And showing such estimation in the app next to the confirmed cases may not be a wise decision and will cause a lot of confusion.

**Comment by nateritter** [comment]
Perhaps a more "advanced" feature where the defaults could be edited would be appropriate?  I still think it's valuable to hypothesize about the true number of cases vs just the reported ones.  And our govt is definitely not intervening in the same way others who have controlled the virus have, so my theory is that we are still in an "uncontrolled" state, at least in my region.

**Comment by MhdHejazi** [comment]
Yes, I think I can add this for advanced users. It's not a high priority right now though, so it may get delayed a little bit.

**Comment by nateritter** [comment]
Totally understandable. Thanks!

**Comment by MhdHejazi** [comment]
So, as of today, there are 22,200 confirmed cases and 278 deaths. The estimated true cases are then:

![2^{17.3/6.18}*(100/0.87)*278=222,440](https://render.githubusercontent.com/render/math?math=2%5E%7B17.3%2F6.18%7D*(100%2F0.87)*278=222,440)

That's 10x the official number.

1. Does this model still make sense?
2. Is it the only number to be shown in the app?

**Comment by nateritter** [comment]
1. It seems to make sense so far. The variables/assumptions may need changing at some point depending on the government and social changes people make, but as of right now, yes, that makes sense.
2. It's definitely a number I'm most concerned with, and I think most people should be concerned with to enact change of behavior.

**Comment by MhdHejazi** [comment]
I added a screen for the estimated true cases. To try it, you have to switch to the new branch ([`feature/true-cases`](https://github.com/MhdHejazi/CoronaTracker/tree/feature/true-cases)) and run the project.

![image](https://user-images.githubusercontent.com/121827/77452150-ab3d4580-6e06-11ea-9d66-083b79115c12.png)

![image](https://user-images.githubusercontent.com/121827/77452245-c3ad6000-6e06-11ea-8b95-3f87f31f463f.png)
