### ISSUE TITLE
Loss of date

### ISSUE THREAD

**Issue by GScottElshaw** [mhdhejazi/CoronaTracker#130]
The date of the day has disappeared from the information included when clicking on each bar. :-(
![Screenshot 2020-07-31 at 6 03 13 PM](https://user-images.githubusercontent.com/69029666/89005376-69924d80-d358-11ea-8daa-59e1a98b4c8c.png)

**Comment by mhdhejazi** [comment]
I think this is fixed on the master. Can you try building from code?

**Comment by GScottElshaw** [comment]
Sorry, I can’t, I’m afraid my HD is full!

Cheers,
Gary

--
"The difficulty now is that unexceptional adults believe the loss of youthful dreaming is itself "growing up," as though adulthood were the passive conclusion to a doomed activity and hope during adolescence."

The Uses of Disorder: Personal Identity and City Life
-- Richard Sennett

OO
[_]<|
/|\

**Comment by mhdhejazi** [comment]
Just released v1.7.2. It has the fix.

**Comment by GScottElshaw** [comment]
Thank you Sir!

Cheers,
Gary

--
"The difficulty now is that unexceptional adults believe the loss of youthful dreaming is itself "growing up," as though adulthood were the passive conclusion to a doomed activity and hope during adolescence."

The Uses of Disorder: Personal Identity and City Life
-- Richard Sennett

OO
[_]<|
/|\
