### ISSUE TITLE
Xcode 11.4 doesn't compile the project

### ISSUE THREAD

**Issue by patricks** [mhdhejazi/CoronaTracker#37]
Since I have updated to Xcode 11.4 I get the following error:

<img width="420" alt="Screen Shot 2020-03-25 at 12 23 01" src="https://user-images.githubusercontent.com/132167/77531535-60b5da80-6e93-11ea-8829-edfee8ae336a.png">

Any ideas how to fix this?

It looks like the 3rd party libraries needs a fix like this one:
https://github.com/onevcat/Kingfisher/pull/1420/files

**Comment by mhdhejazi** [comment]
I'll look into this once my Xcode is updated. It's downloading right now.

**Comment by derekschinke** [comment]
Same issue here, along with a litany of signing issues in Xcode 11.4

**Comment by guidoscheffler** [comment]
I got it to compile following [this thread](https://forums.developer.apple.com/thread/128806).
But since this requires adding
`type: .dynamic`
to the Package.swift files from the CSV and Disk libraries, this is not a solution. A workaround though, for anyone who just wants it to compile.

**Comment by mhdhejazi** [comment]
I forked the repos and added `type: .dynamic` (for [CSV](https://github.com/mhdhejazi/CSV.swift/blob/dynamic/Package.swift) and [Disk](https://github.com/mhdhejazi/Disk/blob/dynamic/Package.swift)). This is a workaround until the libraries are updated.
