### ISSUE TITLE
Can’t build for iOS

### ISSUE THREAD

**Issue by lor1x** [mhdhejazi/CoronaTracker#43]
Hi,

I attached a screenshot of the erros I get during the runtime, if you need log files let me know. 
Tried this on Xcode 11.3.![image](https://user-images.githubusercontent.com/22913459/77589824-b8ccfb00-6eec-11ea-9ddc-422e3e9afe1b.jpeg)

**Comment by mhdhejazi** [comment]
According to the answers [here](https://stackoverflow.com/questions/36533720/failed-to-find-or-create-execution-context-for-description-ibcocoatouchplatform), the following command should fix the problem:

`sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`

If it doesn't help, just restart your Mac.

**Comment by lor1x** [comment]
It doesn’t work...I have already tried that

**Comment by mhdhejazi** [comment]
This is a problem with Xcode and the simulator. I wish I could help you but the project works for me and for other users just fine. Maybe try to use Xcode 11.4?

**Comment by lor1x** [comment]
That’s what I was using.
Maybe because I have it on external drive not on the main one.

Tell me about it...and they won’t fix any of the weird issues popping up everywhere.
