### ISSUE TITLE
Crash on app launch: Can't load 3rd party libraries

### ISSUE THREAD

**Issue by patricks** [mhdhejazi/CoronaTracker#44]
Now #37 is fixed, but if I try to compile and launch the app crashes with the following error:

```
dyld: Library not loaded: @rpath/Disk.framework/Disk
  Referenced from: /private/var/containers/Bundle/Application/146088EE-130F-4790-B27B-021A2DE1FA89/Corona Tracker.app/Corona Tracker
  Reason: image not found
```

**Comment by vordenken** [comment]
I get the following error even after pulling master which should have fixed this(?):

> dyld: Library not loaded: @rpath/Disk.framework/Disk
  Referenced from: /private/var/containers/Bundle/Application/DEBFF1E9-8949-4F86-B855-57CBC52943C9/Corona Tracker.app/Corona Tracker
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/DEBFF1E9-8949-4F86-B855-57CBC52943C9/Corona Tracker.app/Frameworks/Disk.framework/Disk: code signature invalid for '/private/var/containers/Bundle/Application/DEBFF1E9-8949-4F86-B855-57CBC52943C9/Corona Tracker.app/Frameworks/Disk.framework/Disk'

Looks like the same or very similiar.

**Comment by mhdhejazi** [comment]
Yes, it's fixed on the master. Did you try cleaning the project after pulling?

**Comment by vordenken** [comment]
Yes, I even removed my local copy and cloned it fresh again, still the same problem.

**Comment by mhdhejazi** [comment]
I'm using Xcode 11.4 and everything works just fine on iOS 13.4.

Looks like some people were having a similar problem on iOS < 13.4 or older Xcode. See [this](https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830).

**Comment by vordenken** [comment]
My iPhone is on 13.3.1 actually. I will update tomorrow and test it again. Thanks for the info.

**Comment by vordenken** [comment]
Quick update: After installing 13.4 it works!

**Comment by mhdhejazi** [comment]
Glad it works out!
