### ISSUE TITLE
Is dayly statistics removed or...?

### ISSUE THREAD

**Issue by FluffyDev2019** [mhdhejazi/CoronaTracker#47]
In last days I haven't seen the dayly statistics  under (as shown in attatched pic), is it removed or is there something else?

Miss that information troumendssly.

Build I use is from Master.
![E8E2A2E3-8215-427F-9348-64330AE7E0E6](https://user-images.githubusercontent.com/49336613/77682797-c68b8a80-6f97-11ea-8427-499e6713bf01.jpeg)

**Comment by mhdhejazi** [comment]
The problem was from the data source. They changed the files and some parts of the data. I updated the code to work with the new files and handle the missing data for some countries. 

I'll release the new version soon, but if you wish, you can pull/download the code and test the latest version.

**Comment by FluffyDev2019** [comment]
Ok, thx for the update on that.
Will wait eagerly for a updated release.

**Comment by mhdhejazi** [comment]
The new release is out. Could you confirm the problem is solved now?

**Comment by hardkrash** [comment]
Works for me with 1.5
