### ISSUE TITLE
Missing data for Florida

### ISSUE THREAD

**Issue by Maarondesigns** [MhdHejazi/CoronaTracker#5]
![1A0FC1B0-0703-4107-9F25-6B7399440ED7](https://user-images.githubusercontent.com/40376601/76683410-37b36100-65da-11ea-966b-04c93d505c16.jpeg)
![FFCC33A0-2FD2-4299-B026-576C6B146AAA](https://user-images.githubusercontent.com/40376601/76683413-397d2480-65da-11ea-8f47-6695435677f8.jpeg)

App shows no data in Florida. However WHO has cases but location includes County name. Also Colorado. Kansas shows nothing but who has cases there also.

**Comment by MhdHejazi** [comment]
Thanks for letting me know. I'll look into it today.

**Comment by MhdHejazi** [comment]
I added search functionality. So, I've just tried searching for Florida, Kansas, and Colorado, and all of them have data in the app. Would you check it again please?

**Comment by Maarondesigns** [comment]
Yep I can see the data now for Florida, etc. Thanks!
