### ISSUE TITLE
Add support for 10.14

### ISSUE THREAD

**Issue by rjcoelho** [mhdhejazi/CoronaTracker#50]
"You have macOS 10.14.6. The application requires macOS 10.15 or later." Why ?

**Comment by vordenken** [comment]
This app runs on mac using Apples Project Catalyst. It was introduced in macOS 10.15. Thats why it wont work on older versions.

**Comment by rjcoelho** [comment]
I see, too bad, I wanted to use this app but cannot update to 10.15. I'm closing this issue. thanks
