### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by Mozahler** [mhdhejazi/CoronaTracker#54]
I'm getting multiple errors of one particular type:
Type of expression is ambiguous without more context
<img width="1164" alt="Screen Shot 2020-03-29 at 4 49 56 PM" src="https://user-images.githubusercontent.com/9641531/77860665-5a4e9800-71de-11ea-985a-0101d7dfe9a6.png">
<img width="855" alt="Screen Shot 2020-03-29 at 4 53 41 PM" src="https://user-images.githubusercontent.com/9641531/77860672-60dd0f80-71de-11ea-8a66-b05d725486f9.png">

Did I miss a step? I downloaded the zip. It fetched the packages without errors when I built it.

**Comment by djimberry** [comment]
having the same issues

**Comment by mhdhejazi** [comment]
You need to use the latest Xcode 11.4 that comes with Swift 5.2

**Comment by Mozahler** [comment]
Thanks. I'll close this.

**Comment by fuerst** [comment]
Xcode 11.4 doesn't run on macOS 10.14 (Mojave). So anyone not using macOS 10.15 (Catalina) can not compile this app.

**Comment by mhdhejazi** [comment]
I reversed some changes I previously made to the code to make it compatible again with Xcode 11.3.
Let me know if it works now.

**Comment by fuerst** [comment]
It works now - thanks a lot!
