### ISSUE TITLE
No live map

### ISSUE THREAD

**Issue by Tijnderivecourt** [mhdhejazi/CoronaTracker#59]
On the application I can't see the map with live stats. I can see all the graphs. Just not the map.
iPhone 11 Pro Max iOS 13.3

**Comment by mhdhejazi** [comment]
Could you add a screenshot and more info about the environment (Xcode version, OS version, Device)?

**Comment by mhdhejazi** [comment]
Duplicate of #60

**Comment by Tijnderivecourt** [comment]
Dear Hejazi,

It's already fixed after I set the automatic time to manual! Maps now
working and everything is fine.

Thanks in advance!

Met vriendelijke groet,
Tijn de Rivecourt

**Comment by mhdhejazi** [comment]
Well, that is weird! But glad you worked this out.
