### ISSUE TITLE
Build Mac APP have problem

### ISSUE THREAD

**Issue by thinkinnight** [MhdHejazi/CoronaTracker#6]
Build iPhone APP is OK, but while build mac app, it have internal error. Do not know why.

<img width="1501" alt="Snipaste_2020-03-14_22-37-02" src="https://user-images.githubusercontent.com/767663/76684176-a62d0900-6644-11ea-8694-8d2146befa0f.png">

**Comment by MhdHejazi** [comment]
I think cleaning the project may do the trick:
1. Clean the project (Product > Clean Build Folder).
2. Restart Xcode.
3. Build again.

Let me know if the problem is resolved.

**Comment by thinkinnight** [comment]
Thanks for your quick reply.
I have tried the steps suggested, but still have the same problem...

**Comment by MhdHejazi** [comment]
Strange. I'm using Xcode 11.3.1 and it works just fine.

In the screenshot above it says "File a bug and attach '/var/folders/....'". If you can send me that file I can look into it and hopefully figure out what's wrong.

**Comment by hanksudo** [comment]
Works fine here. also Xcode 11.3.1
