### ISSUE TITLE
Maps does not load white screen

### ISSUE THREAD

**Issue by an20olives** [mhdhejazi/CoronaTracker#60]
Currently running into issues with the maps screen not loading it just appears white.

**Comment by mhdhejazi** [comment]
Could you add a screenshot and more info about the environment (Xcode version, OS version, Device)?

**Comment by an20olives** [comment]
Sure, its an iPhone 11 Pro Max on iOS 13.3. What occurs is this https://imgur.com/gallery/GbA6QKI 
Xcode version is 11.4

**Comment by mhdhejazi** [comment]
I don't have iPhone 11 Pro Max, but the app works very well on the simulator. I'm not able to reproduce this issue so I can't figure out what's wrong.

**Comment by Theo-rhone** [comment]
Hello, 

Yes I have the same problem on iPhone 11 Max Pro (13.3.1). I think who need to install 13.4.  

The problem is due to the package disk (code signature invalid)
```
Reason: no suitable image found.  Did find:   
	/private/var/containers/Bundle/Application/CCAEF2C6-E029-4B8C-A0FA-320F84893F34/Corona Tracker.app/Frameworks/Disk.framework/Disk: code signature invalid for '/private/var/containers/Bundle/Application/CCAEF2C6-E029-4B8C-A0FA-320F84893F34/Corona Tracker.app/Frameworks/Disk.framework/Disk'
```

**Comment by jsf030** [comment]
Cheers!
https://stackoverflow.com/a/60090629

**Comment by mhdhejazi** [comment]
So from the above link:
>You can:
>1. Use a non-Personal Team provisioning profile (paid developer account).
>3. Test on a real iOS device running 13.3 or lower.
>5. Wait for iOS 13.4 to be released.

If you can't upgrade to 13.4, the only remaining solution is to:
1. Remove the widget target from the project.
2. Change the location of Disk and CSV.swift packages to their original sources (Remove and add again):

![image](https://user-images.githubusercontent.com/121827/78111272-1c7f8880-7405-11ea-89ae-3dd8b1e349ff.png)

**Comment by mhdhejazi** [comment]
Another possible solution is mentioned here: https://github.com/mhdhejazi/CoronaTracker/issues/59#issuecomment-607296795
