### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by vijayamin83** [mhdhejazi/CoronaTracker#66]
Getting the "Type of expression is ambiguous without more context" in the latest build.

Check the screen shot
![Screenshot 2020-04-02 at 12 19 31 PM](https://user-images.githubusercontent.com/468540/78218940-40fa6400-74dc-11ea-85e8-85749ae08a59.png)

**Comment by mhdhejazi** [comment]
This is a duplicate of #54

**Comment by mhdhejazi** [comment]
Duplicate of #54
