### ISSUE TITLE
The data is not updated

### ISSUE THREAD

**Issue by frakman1** [mhdhejazi/CoronaTracker#67]
Platform: iPhone SE 
iOS: 10.3.2

I just updated to the latest version today and am running into this issue on my phone.
```Can't update the data. Please make sure you're connected to the internet```

Of course I've checked and my phone is online and all other apps are able to connect to the internet.
I also checked via Cellular, WiFi and even VPN and I always get the same error.

![image](https://user-images.githubusercontent.com/5826484/78278151-9be38980-74e3-11ea-8fe6-5aa2b369026c.png)

**Comment by helmarw** [comment]
yes was working couple of hours ago, i just checked again, but nothing now.
on Mac and iPhone. I compiled v1.5 a couple of days ago

**Comment by mhdhejazi** [comment]
It looks like the data format has changed from the data source. I'm looking into that.

**Comment by mhdhejazi** [comment]
The issue is now fixed on the master. I'll make an update for macOS users.

**Comment by helmarw** [comment]
k, ill have a look

**Comment by derekschinke** [comment]
same issue

**Comment by frakman1** [comment]
@helmarw Glad it's not just me. 
@mhdhejazi Thank you. It's working now.

**Comment by helmarw** [comment]
works for me on mac and iphone, thnx !!!

**Comment by mhdhejazi** [comment]
Glad it works.

I'll reopen the issue so other people know it's fixed now and they only need to update.

**Comment by helmarw** [comment]
hi, I tried to compile the latest version for iPhone but im getting this error msg:
"The maximum number of apps for free development profiles has been reached."

I only have one app on it that I compiled myself, that's the Corona Tracker.
Also after deleting and rebooting I cant install the new version. I tried googling it
but so far I did not find any solution ..

sorry its a bit off topic but maybe its just something stupid I missed
