### ISSUE TITLE
Overlapping labels in state view for "Most Affect Countries"

### ISSUE THREAD

**Issue by derekschinke** [mhdhejazi/CoronaTracker#69]
![image](https://user-images.githubusercontent.com/16145903/78314028-871beb80-750d-11ea-87e1-551503e54dfa.png)

Occurs on iOS and macOS.

**Comment by mhdhejazi** [comment]
I see. This is caused by missing time series data for some locations. I'll work on a fix.

**Comment by mhdhejazi** [comment]
It's fixed on the master.
