### ISSUE TITLE
Plus-minus sign for death cases

### ISSUE THREAD

**Issue by erickzli** [mhdhejazi/CoronaTracker#70]
Version 1.6 Mac

When I checked the situation in the US, it showed that the increment of death cases in the US was “+-15”. I guess it is caused by the decrease of reported death cases (needs to be confirmed by checking the dataset)? I’ve attached the screenshot, please notice the US death cases.

<img width="318" alt="Screen Shot 2020-04-02 at 8 24 59 PM" src="https://user-images.githubusercontent.com/17897676/78314903-11ba1600-7521-11ea-8d14-efd17024092f.png">

**Comment by Yonodactyl** [comment]
I submitted a PR [71](https://github.com/mhdhejazi/CoronaTracker/pull/71) that may or may not address this. I hope to get a review on it.

**Comment by mhdhejazi** [comment]
When this happens it must be a problem with the data source as the difference in total deaths between yesterday and today can never be a negative number.

Everything should be fine again when the data is corrected, but the negative numbers shouldn't be shown in such cases.

**Comment by erickzli** [comment]
Yes, I see. I will close this issue. Thank you!
