### ISSUE TITLE
Search icon not visible

### ISSUE THREAD

**Issue by frakman1** [MhdHejazi/CoronaTracker#8]
When using iPhone SE iOS 10.3, the search icon is not visible despite being clickable.

![Simulator Screen Shot - iPhone SE (iOS 10 3) - 2020-03-14 at 18 57 29](https://user-images.githubusercontent.com/5826484/76691960-b504c300-6626-11ea-9df4-3d43dfd948d1.png)

**Comment by MhdHejazi** [comment]
Thanks for letting me know.
It should be fixed on the master now.
