### ISSUE TITLE
doesnt work on ipad

### ISSUE THREAD

**Issue by helmarw** [mhdhejazi/CoronaTracker#80]
i tried to compile it for my ipad (5. Generation), but the app crashes as soon as i try to start it.
i only tried it on my ipad because when i try recompiling it for my iPhone6s im getting 
this error msg: The maximum number of apps for free development profiles has been reached.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620383

i only had the corona tracker on my iphone, nothing else which i compiled myself.
i deleted an older version, rebooted but still the same. i dont know how to solve this.
everything i found with google didnt help, any help welcome...

thnx
Helmar

**Comment by helmarw** [comment]
i finally found out what i had to do to get it back on the iPhone.

issue about the iPad had nothing to do with it, iPad still not working ...

**Comment by Yonodactyl** [comment]
I know you mentioned you don’t have anything else installed — have you EVER installed another development app on this account?

**Comment by Yonodactyl** [comment]
The app is probably written for version of iOS that might not be supported. This or the app doesn’t have anything to fallback to and a certain method is causing the app to crash.

**Comment by helmarw** [comment]
sorry, I dont understand what you are talking about, the iOS version on iPad is the same as on my iPhone6s. The Problem with my iPhone was to many certificates (dont know where the came from). Anyway took me a while to find how to get rid of them, simply deleting all self compiled apps (as often posted) does not help at all, that's simply BS. And shit docu from apple, or should I say non existing actually ... no help via Apples Feedback Assistant of course, didn't expect anything else though ;)

anyway on the iPad its a different issue, I can compile and upload it, trust my own profile of course but then the app starts and closes, that's all, not getting any error messages anywhere as far as I know, or at least I dont know where to look for them.
Just wanted to let the developer know what's happening, maybe they want to look into it, or I did some stupid mistake somewhere, I dont know.
Its working on iPhone and Mac for me so far...

**Comment by helmarw** [comment]
an other comment: it works in the simulator with iPad (5.th Genration) as target

**Comment by mhdhejazi** [comment]
I just tried it on an iPad and it works just fine.

What do you see when the app closes?

**Comment by helmarw** [comment]
not much, screen goes white for a second and then its gone ...

**Comment by mhdhejazi** [comment]
Do you run the app from Xcode? What do you see in the console?

**Comment by helmarw** [comment]
i took an other shot, unpaired the device, rebooted, cleaned build folder, paired the ipad again,
checked that all provisioning profiles were gone and compiled it again.
now its working, very strage ...
still dont know exactly what the problem was, but its working now, thnx ! 👍

**Comment by mhdhejazi** [comment]
Glad it worked out!
