### ISSUE TITLE
Small errors in diagrams

### ISSUE THREAD

**Issue by jsf030** [mhdhejazi/CoronaTracker#82]
I noticed a few little things:

- In the diagram of the most affected countries, the 100,000 steps are different sizes. The first 100,000 are smaller than the subsequent ones, which distorts the diagram and makes the USA appear even more disproportionate in this case. This also applies to the full screen view after tapping.

- There also seems to be some kind of rounding error. In the diagram of the worldwide development of cases, the same applies to the same extent as to individual countries such as Slovenia, which has just over 1,000 cases. In the case of the worldwide case development, 1.1 million cases become 1 million, in Slovenia 1,100 cases become 1,000 cases. After rounding, both cases are therefore shown twice with step 1 million and 1,000 respectively.

**Comment by mhdhejazi** [comment]
Thank you for reporting the issues. They are fixed on the master.

**Comment by mhdhejazi** [comment]
I want to also appreciate your attention to the details. Very few people will notice the second issue and report it 👍
