### ISSUE TITLE
feature suggestion - log scale graphs

### ISSUE THREAD

**Issue by Jimmysnielsen** [mhdhejazi/CoronaTracker#89]
I suggest the option for graphing "daily new cases" on a log scale graph, possibly also useful for other graphs as well.

**Comment by mhdhejazi** [comment]
The option is already available for the other graphs. But why do you think it should be used for graphing "daily new cases"?

**Comment by Jimmysnielsen** [comment]
hi,
looking at China, e.g., it is very difficult to see the current rate of new infections  when the scale is governed by the highest rate of infections.

[cid:85de4ec6@ginishi.dk]

Med venlig Hilsen / Kind regards

Jimmy S. Nielsen

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mhdhejazi** [comment]
There is a "daily new cases" chart just for China (when you tap on the country name). Am I missing something here?

**Comment by Jimmysnielsen** [comment]
the problem is the scales. Here is the graph for China. Owing to the peak at 15k the last months data are so small compared that it is practically impossible to get any information from the graph.

[cid:72c7c352@ginishi.dk]

Med venlig Hilsen / Kind regards

Jimmy S. Nielsen

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mhdhejazi** [comment]
Good point.
I added a logarithmic scale option to the chart. I guess it's now far clearer.
![image](https://user-images.githubusercontent.com/121827/79845669-135f5700-83c6-11ea-90e4-9bda15bc9265.png)

**Comment by mhdhejazi** [comment]
The same chart with a scale that starts from 10 (10^1) instead of 1 (10^0).
Do you think it's better?

![image](https://user-images.githubusercontent.com/121827/79845933-781ab180-83c6-11ea-9c7a-394c6253f938.png)

**Comment by Jimmysnielsen** [comment]
starting from ten will probably work for most countries.
I suppose that the best possible solution would be to generate the scale based on the data.

Med venlig Hilsen / Kind regards

Jimmy S. Nielsen

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
