### ISSUE TITLE
Can't scroll region view anymore 

### ISSUE THREAD

**Issue by ryans-git** [MhdHejazi/CoronaTracker#9]
Scrolling up to see the region view controller was broken in the update v1.3 for iPhone 8 and 8 plus. Only the top of the graph can be seen.

e13ee1846563bc7e1d1f0ecd2db5a98d2c9f6c79

Scroll seems to be broken on all iPhones actually. Just that the graphs can still be seen on the bigger screens.

**Comment by MhdHejazi** [comment]
It's fixed on the master now. Thanks for reporting the issue!

**Comment by ryans-git** [comment]
works great! thanks for the quick fix
