### ISSUE TITLE
"Tracker" App

### ISSUE THREAD

**Issue by MadTed** [mhdhejazi/CoronaTracker#97]
Hi there,

you name you're app a somehow "tracker".
For me this is confusing.
Now they started to develop real tracker apps, to track down people who are infected with
covid-19 and tracking their contacts.
Your app is only a dashboard, or?
So I would like to suggest to take out the "tracking" term from your repository.

What do you think about that?

Greets,
Ted

P.S.: I started to develop such a tracking app.
https://github.com/MadTed/PD-Tracking-App-hackthepandemic/blob/master/description_of_the_app.txt
And of course, it should also have a dashboard. Perhaps you like to contribute?

**Comment by mhdhejazi** [comment]
Actually, it's not only this app, but there are also similar projects that use a similar name.
What you're talking about is called contact tracing not tracking, and multiple countries are working on their own contact tracing apps.

I'm closing the issue. Thanks for bringing this into my attention.
